language: generic

matrix:
  include:
    - os: osx
      osx_image: xcode12.0
      compiler: clang
    - os: linux
      sudo: false
      addons:
        apt:
          sources:
           - ubuntu-toolchain-r-test
          packages:
           - libstdc++-6-dev

script:
  - ./mason build ${MASON_NAME} ${MASON_VERSION}
- ./mason publish ${MASON_NAME} ${MASON_VERSION}
