version: ~> 1.0

language: generic

dist: precise

os: linux

install:
- |
  if [[ ${MASON_PLATFORM:-unset} == 'unset' ]] || [[ ${MASON_PLATFORM} == 'osx' ]] || [[ ${MASON_PLATFORM} == 'linux' ]]; then
    # If platform is Linux or OSX, we might still be cross compiling if the
    # MASON_PLATFORM_VERSION is not the same as the host platform.
    if [[ ${MASON_PLATFORM_VERSION} == `uname -m` ]] || [[ -z ${MASON_PLATFORM_VERSION} ]]; then
      echo "Installing clang for OSX/Linux via 'install' target"
      source utils/toolchain.sh
      which ${CC}
      ${CC} -v
      which ${CXX}
      ${CXX} -v
    fi
  fi

script:
- |
  if [[ ${SYMLINK_INSTALL:-} == true ]]; then
    mkdir -p custom/path
    ln -s $(pwd)/mason $(pwd)/custom/path/mason
    export PATH=$(pwd)/custom/path:${PATH}
    MASON_CUSTOM_PATH=true ./test/all.sh
  else
    ./test/all.sh;
  fi
