language: generic

matrix:
  include:
    - os: osx
      osx_image: xcode7.3
      compiler: clang
    - os: linux
      sudo: false
      addons:
        apt:
          sources:
           - ubuntu-toolchain-r-test
          packages:
           - libstdc++6
           - libstdc++-5-dev

install:
- source utils/toolchain.sh
- ${CC} --version
- ${CXX} --version

script:
- ./test/all.sh
