language: generic

matrix:
  include:
    - os: osx
      osx_image: xcode7.3
      compiler: clang
    - os: linux
      sudo: false
      addons:
        apt:
          sources:
           - ubuntu-toolchain-r-test
          packages:
           - libstdc++6
           - libstdc++-5-dev

install:
- |
  if [[ ${MASON_PLATFORM:-unset} == 'unset' ]] || [[ ${MASON_PLATFORM} == 'osx' ]] || [[ ${MASON_PLATFORM} == 'linux' ]]; then
    echo "Installing clang for OSX/Linux via 'install' target"
    source utils/toolchain.sh
    which ${CC}
    ${CC} -v
    which ${CXX}
    ${CXX} -v
  fi

script:
 # put mason at symlink to simulate historically recommended install method
 - mkdir -p custom/path
 - ln -s $(pwd)/mason $(pwd)/custom/path/mason
 - export PATH=$(pwd)/custom/path:${PATH}
 - ./test/all.sh
