language: cpp

sudo: false

os:
  - linux
  - osx

env:
  matrix:
    - TEST="unit"
    - TEST="c_install"
    - TEST="c_build"
    - TEST="c_install_symlink_includes"
    - TEST="cpp11_header_install"
    - TEST="cpp11_install"
    - TEST="cpp11_build"
    - TEST="c_build_android"

install:
# NOTE: must be absolute path for predictable behavior
# when packages call out to mason themselves in order to install deps
- export MASON_DIR=$(pwd)

script:
- ./test/${TEST}.sh
