language: cpp

sudo: false

matrix:
  include:
    - os: osx
      compiler: clang
    - os: linux
      compiler: clang

env:
  global:
   - secure: "clCFM3prHnDocZ8lXlimPxAogvFirD1Zx8cMcFJ/XpkTA/0pCgnhpArM4y/NzLHR57pNZTSCr3p6XZI1c1iTG4Zm8x0sK2A4aTFRahypXNy/e+LzAbtd1y1+dEEDwlJvNNGxizQX4frhOgSNQFDFnWLtmF3stlft5YWyc2kI+FI="
   - secure: "jKJErCng8Sk8YJ0IN2FX3lhv7G1LeudMfFBAXViZaXn8w/gWPs+SlfXQmIJ5SruU7U2GQKnAhzbjwXjVAgAh8OAblzny0DDm5Lh5WmwkgAP8JH1LpsBwCYx2S/v8qyR4DX1RVhHS8mQu298180ZDVgGccw+hd8xrE/S5TEQcNfQ="

before_install:
- git clone --depth=1 https://github.com/mapbox/mason.git ~/.mason

script:
- ./script.sh build
- ./test.sh

# postgis must be source compiled on top of postgres to work currently
# so we don't actually want to package binaries for it - they don't make
# sense yet
#after_success:
#- ./script.sh publish
