language: generic

matrix:
  include:
    - os: osx
      osx_image: xcode8
      compiler: clang
    - os: linux
      sudo: false

install:
- |
  if [[ ${MASON_PLATFORM:-unset} == 'unset' ]] || [[ ${MASON_PLATFORM} == 'osx' ]] || [[ ${MASON_PLATFORM} == 'linux' ]]; then
    # If platform is Linux or OSX, we might still be cross compiling if the
    # MASON_PLATFORM_VERSION is not the same as the host platform.
    if [[ ${MASON_PLATFORM_VERSION} == `uname -m` ]] || [[ -z ${MASON_PLATFORM_VERSION} ]]; then
      echo "Installing clang for OSX/Linux via 'install' target"
      source utils/toolchain.sh
      which ${CC}
      ${CC} -v
      which ${CXX}
      ${CXX} -v
    fi
  fi

script:
- ./test/all.sh
# Below we test installing based on the recommended method
# get the latest tag
- TAG_NAME=$(cat mason | grep MASON_RELEASED_VERSION= | cut -c25-29)
# Test installing via curl to /tmp
- curl -sSfL https://github.com/mapbox/mason/archive/v${TAG_NAME}.tar.gz | tar --gunzip --extract --strip-components=1 --exclude="*md" --exclude="test*" --directory=/tmp
# ensure the command works
- ./tmp/mason install zlib 1.2.8