language: cpp
sudo: false

os:
  - linux
  - osx

env:
  global:
   - secure: "clCFM3prHnDocZ8lXlimPxAogvFirD1Zx8cMcFJ/XpkTA/0pCgnhpArM4y/NzLHR57pNZTSCr3p6XZI1c1iTG4Zm8x0sK2A4aTFRahypXNy/e+LzAbtd1y1+dEEDwlJvNNGxizQX4frhOgSNQFDFnWLtmF3stlft5YWyc2kI+FI="
   - secure: "jKJErCng8Sk8YJ0IN2FX3lhv7G1LeudMfFBAXViZaXn8w/gWPs+SlfXQmIJ5SruU7U2GQKnAhzbjwXjVAgAh8OAblzny0DDm5Lh5WmwkgAP8JH1LpsBwCYx2S/v8qyR4DX1RVhHS8mQu298180ZDVgGccw+hd8xrE/S5TEQcNfQ="
  matrix:
   - MASON_PLATFORM=android
   - MASON_PLATFORM=linux

before_install:
- git clone --depth=1 https://github.com/mapbox/mason.git ~/.mason
- if [ "${MASON_PLATFORM}" = "android" ]; then MASON_PLATFORM= ~/.mason/mason install 7z 9.20; export PATH=$(MASON_PLATFORM= ~/.mason/mason prefix 7z 9.20)/bin:${PATH}; wget http://dl.google.com/android/ndk/android-ndk-r10c-linux-x86_64.bin; chmod a+x ./android-ndk-r10c-linux-x86_64.bin; 7z x ./android-ndk-r10c-linux-x86_64.bin; export ANDROID_NDK_PATH=$(pwd)/android-ndk-r10c; ls -l;ls -l $ANDROID_NDK_PATH; fi;

script:
- ./script.sh build

after_success:
- ./script.sh publish
