language: generic

matrix:
  include:
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
           - ubuntu-toolchain-r-test
          packages:
           - libstdc++-5-dev
           - llvm-6-dev
           - llvm-6-tools
           - python3-pip
           - pkg-config
           - libdrm-dev
           - elfutils
           - libelf-dev
           - bison
           - flex
           - libwayland-dev
           - wayland-protocols
           - libwayland-egl-backend-dev
           - libx11-dev
           - libxext-dev
           - libxdamage-dev
           - libxcb-glx0-dev
           - libx11-xcb-dev
           - libxcb-dri2-0-dev
           - libxcb-dri3-dev
           - libxcb-present-dev
           - libxshmfence-dev
           - libxxf86vm-dev
           - libxrandr-dev
           - gettext
           - ninja-build

script:
- ./mason build ${MASON_NAME} ${MASON_VERSION}

after_success:
- ./mason publish ${MASON_NAME} ${MASON_VERSION}
