language: generic

matrix:
  include:
    - os: osx
      osx_image: xcode9.2
    - os: linux
      sudo: false

script:
- ./mason build ${MASON_NAME} ${MASON_VERSION}
- ./mason publish ${MASON_NAME} ${MASON_VERSION}
