language: generic

matrix:
  exclude:
    - os: linux
    - os: osx
  include:
    - os: osx
      osx_image: xcode11
    - os: linux
      sudo: false
      dist: bionic
      addons:
        apt:
          packages: [ 'libstdc++-7-dev' ]

script:
- ./mason build ${MASON_NAME} ${MASON_VERSION}
- ./mason publish ${MASON_NAME} ${MASON_VERSION}
