language: C

sudo: false

matrix:
  include:
    - os: osx
      compiler: clang
    - os: linux
      compiler: clang

addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
     - llvm-toolchain-precise-3.5
    packages:
     - clang-3.5

before_install:

script:
- export CXX="clang++-3.5"
- ./mason build ${MASON_NAME} ${MASON_VERSION}

after_success:
- ./mason publish ${MASON_NAME} ${MASON_VERSION}
