language: cpp

sudo: false

compiler: clang

matrix:
  include:
    - os: linux
    - os: osx

before_install:

script:
- ./mason build ${MASON_NAME} ${MASON_VERSION}

after_success:
- ./mason publish ${MASON_NAME} ${MASON_VERSION}
