language: cpp

sudo: false

matrix:
  include:
    - os: osx
      osx_image: xcode6
      compiler: clang
    - os: osx
      osx_image: xcode7
      compiler: clang
    - os: linux
      compiler: clang

before_install:
- source ./scripts/setup_cpp11_toolchain.sh

script:
- ./mason build ${MASON_NAME} ${MASON_VERSION}

after_success:
- ./mason publish ${MASON_NAME} ${MASON_VERSION}
