language: cpp

sudo: false

matrix:
  include:
    - os: osx
      osx_image: xcode6
      compiler: clang
    - os: osx
      osx_image: xcode7
      compiler: clang
    - os: linux
      compiler: clang

addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
    packages:
     - g++-5

before_install:
- export CC=/usr/bin/gcc-5
- export CXX=/usr/bin/g++-5
- export MASON_CONCURRENCY_OVERRIDE=2

script:
- ./mason build ${MASON_NAME} ${MASON_VERSION}

after_success:
- ./mason publish ${MASON_NAME} ${MASON_VERSION}
