language: cpp

sudo: false

matrix:
  include:
    - os: osx
      compiler: clang
    - os: linux
      compiler: clang

before_install:
- source ./scripts/setup_cpp11_toolchain.sh

script:
- ./mason build ${MASON_NAME} ${MASON_VERSION}
- ./mason link ${MASON_NAME} ${MASON_VERSION}
- ./test.sh

after_success:
- ./mason publish ${MASON_NAME} ${MASON_VERSION}
